const translations = {
 fa: {
 tagline:'ترجمهٔ زنده و تایپ صوتی با کلید خودت', beta:'آزمایشی', settings:'تنظیمات', back:'بازگشت به دوبله', target:'زبان دوبله', original:'صدای اصلی تب', dub:'صدای دوبله', volumeHint:'بلندی هر صدا را حتی هنگام دوبله تغییر بده؛ صفر یعنی بی‌صدا.', start:'شروع دوبلهٔ این تب', stop:'توقف', transcript:'متن ترجمه', empty:'ترجمهٔ گفتار اینجا نمایش داده می‌شود…', waiting:'منتظر گفتار تب…', uiLanguage:'زبان افزونه', key:'کلید API گوگل', keyHint:'کلید روی همین دستگاه ذخیره می‌شود و با بستن مرورگر یا خاموش‌کردن رایانه پاک نمی‌شود. تغییر کلید از شروع بعدی اعمال می‌شود.', getKey:'دریافت کلید از Google AI Studio ↗', save:'ذخیرهٔ کلید', delete:'حذف کلید', saved:'کلید ذخیره شد.', deleted:'کلید ذخیره‌شده حذف شد. جلسهٔ جاری تا توقف ادامه دارد.', missing:'کلید API خود را در تنظیمات وارد و ذخیره کنید.', notice:'با شروع ترجمه، صدای همین تب به گوگل ارسال می‌شود؛ با شروع تایپ صوتی، صدای میکروفن ارسال می‌شود. مصرف API از حساب شماست.', independent:'Dubly یک افزونهٔ مستقل است و وابسته به Google LLC نیست و مورد تأیید یا حمایت آن قرار ندارد. این افزونه صرفاً از Gemini API با کلید Google AI Studio شما استفاده می‌کند.', idle:'آمادهٔ شروع', connecting:'در حال اتصال به گوگل…', live:'دوبله روشن است • در انتظار یا دریافت گفتار', error:'دوبله متوقف شد', connectionError:'ارتباط با افزونه قطع شد؛ پنجره را دوباره باز کنید.', startError:'شروع دوبله ناموفق بود. دوباره امتحان کنید.', stopError:'توقف ناموفق بود؛ افزونه را دوباره بارگذاری کنید.', volumeError:'تنظیم صدا ناموفق بود؛ دوباره امتحان کنید.', saveError:'ذخیرهٔ تنظیمات ناموفق بود.', loadError:'خواندن تنظیمات ناموفق بود.'
 },
 en: {
 tagline:'Live translation and Voice Typing with your key', beta:'Beta', settings:'Settings', back:'Back to dubbing', target:'Dubbing language', original:'Original tab volume', dub:'Dubbed audio volume', volumeHint:'Adjust either volume while dubbing. Zero mutes that audio.', start:'Start dubbing this tab', stop:'Stop', transcript:'Translation transcript', empty:'Translated speech will appear here…', waiting:'Waiting for tab speech…', uiLanguage:'Interface language', key:'Google API key', keyHint:'Your key is saved on this device and stays after closing the browser or restarting your computer. Key changes apply to the next session.', getKey:'Get a key from Google AI Studio ↗', save:'Save key', delete:'Delete key', saved:'Key saved.', deleted:'Saved key deleted. The current session continues until stopped.', missing:'Enter and save your API key in Settings.', notice:'Starting translation sends this tab’s audio to Google; starting Voice Typing sends microphone audio. API usage is charged to your account.', independent:'Dubly is an independent extension, not affiliated with, endorsed by, or sponsored by Google LLC. It uses the Gemini API with your Google AI Studio key.', idle:'Ready to start', connecting:'Connecting to Google…', live:'Dubbing is on • Listening for speech', error:'Dubbing stopped', connectionError:'Extension connection lost. Reopen this window.', startError:'Could not start dubbing. Please try again.', stopError:'Could not stop. Reload the extension.', volumeError:'Could not adjust volume. Please try again.', saveError:'Could not save settings.', loadError:'Could not read settings.'
 }
};
const englishErrors = [
 ['در حال اتصال…','Connecting…'], ['افزونه را روی یک صفحهٔ معمولی وب باز کنید.','Open the extension on a regular web page.'], ['کلید API را وارد کنید.','Enter an API key.'], ['دریافت صدای تب پایان یافت.','Tab audio capture ended.'], ['پاسخ صوتی نامعتبر است.','Invalid audio response.'], ['تأخیر پخش بیش از حد شد؛ دوبله را دوباره شروع کنید.','Playback delay is too high. Restart dubbing.'], ['مهلت اتصال تمام شد. اینترنت و دسترسی API را بررسی کنید.','Connection timed out. Check your network and API access.'], ['سرعت اتصال برای دوبلهٔ زنده کافی نیست.','The connection is too slow for live dubbing.'], ['گوگل درخواست را نپذیرفت. کد: ','Google rejected the request. Code: '], ['نامشخص','unknown'], ['جلسهٔ گوگل رو به پایان است؛ دوبله را دوباره شروع کنید.','The Google session is ending. Restart dubbing.'], ['پردازش پاسخ صوتی ناموفق بود.','Could not process the audio response.'], ['اتصال گوگل بسته شد (کد ','Google connection closed (code '], ['اینترنت، کلید و دسترسی مدل را بررسی کنید و دوباره شروع کنید.','Check your network, key and model access, then try again.'], ['دریافت صدای تب یا راه‌اندازی صدا ناموفق بود. پخش صدای تب را بررسی کنید و دوباره امتحان کنید.','Could not capture tab audio or initialize playback. Check tab audio playback and try again.'], ['نمایش زیرنویس در این صفحه توسط Chrome مجاز نیست.','Chrome does not allow captions on this page.'], ['کلید پنهان شد','key hidden']
];
Object.assign(translations.fa, {natural:'طبیعی و روان', mixer:'تلفیق و کنترل صدا', manualMix:'تنظیم مستقل صدا', translated:'ترجمه‌شده', configuration:'پیکربندی هوش مصنوعی و افزونه', appearance:'تم ظاهری افزونه', themeHint:'ظاهر دلخواه پنجرهٔ افزونه را انتخاب کنید.', dark:'تاریک', light:'روشن', auto:'سیستم', home:'ترجمه', keyStored:'کلید ذخیره‌شده', keyEmpty:'کلیدی ثبت نشده', showKey:'نمایش کلید', hideKey:'پنهان‌کردن کلید', captions:'نمایش متن ترجمه'});
Object.assign(translations.en, {natural:'Natural & fluent', mixer:'Audio mixer', manualMix:'Independent volumes', translated:'Translated', configuration:'AI & extension settings', appearance:'Appearance theme', themeHint:'Choose the appearance of your extension.', dark:'Dark', light:'Light', auto:'System', home:'Translate', keyStored:'Key saved', keyEmpty:'No saved key', showKey:'Show API key', hideKey:'Hide API key', captions:'Show transcript'});
Object.assign(translations.fa, {supportTitle:'از Dubly لذت می‌بری؟',supportHint:'با حمایت اختیاری به ادامهٔ توسعه کمک کن',topDonate:'حمایت از توسعهٔ Dubly',activity:'فعالیت من',guide:'راهنمای شروع',privacy:'حریم خصوصی',terms:'شرایط استفاده',support:'پشتیبانی',about:'دربارهٔ Dubly',needHelp:'کمک لازم داری؟',supportShortcutHint:'راهنما و راه ارتباطی با سازنده در این بخش است.',supportShortcut:'باز کردن پشتیبانی ↗',sessionLimit:'توقف خودکار جلسه',noLimit:'بدون محدودیت زمانی',limitHint:'از شروع بعدی اعمال می‌شود. زمان‌سنج، صورت‌حساب گوگل نیست.',activityHint:'فعالیت روی دستگاه ثبت می‌شود؛ مدیریت یا حذف سابقه ↗'});
Object.assign(translations.en, {supportTitle:'Enjoying Dubly?',supportHint:'Help development with an optional donation',topDonate:'Support Dubly development',activity:'My Activity',guide:'Getting started',privacy:'Privacy',terms:'Terms',support:'Support',about:'About Dubly',needHelp:'Need help?',supportShortcutHint:'Find the guide and publisher contact options here.',supportShortcut:'Open support ↗',sessionLimit:'Automatic session stop',noLimit:'No time limit',limitHint:'Applies to the next session. The timer is not a Google bill.',activityHint:'Activity stays on this device. Manage or erase history ↗'});
Object.assign(translations.fa,{testKey:'بررسی اتصال به مدل',testing:'در حال بررسی…',verified:'اتصال به مدل تأیید شد',testFailed:'اتصال تأیید نشد؛ کلید، سهمیه و دسترسی شبکه را بررسی کنید.'});
Object.assign(translations.en,{testKey:'Test model connection',testing:'Testing…',verified:'Model connection verified',testFailed:'Connection not verified. Check the key, quota and network access.'});
Object.assign(translations.fa,{outputMode:'تنظیمات ترجمه',outputType:'نوع خروجی',floatingSubtitles:'فقط زیرنویس شناور',sourceAuto:'تشخیص زبان ورودی: خودکار',subtitlesOnly:'فقط زیرنویس شناور',subtitlesDeveloping:'زیرنویس شناور',floatingExperimental:'زیرنویس شناور',experimentalBadge:'',dubbingOnly:'فقط دوبله',bothOutputs:'دوبله و زیرنویس هم‌زمان',modeHint:'صدای دوبله، زیرنویس شناور یا هر دو را برای صدای تب انتخاب کنید.',start:'شروع ترجمهٔ این تب',target:'زبان ترجمه',captions:'نمایش متن در پنجرهٔ افزونه',live:'ترجمه روشن است • در انتظار یا دریافت گفتار'});
Object.assign(translations.en,{outputMode:'Translation settings',outputType:'Output type',floatingSubtitles:'Floating captions only',sourceAuto:'Source language: Auto-detect',subtitlesOnly:'Floating captions only',subtitlesDeveloping:'Floating captions',floatingExperimental:'Floating captions',experimentalBadge:'',dubbingOnly:'Dubbing only',bothOutputs:'Dubbing and captions',modeHint:'Choose dubbed audio, floating captions, or both for the tab audio.',start:'Start translating this tab',target:'Translation language',captions:'Show text in the extension popup',live:'Translation is on • Listening for speech'});
Object.assign(translations.fa,{setupWelcome:'دوبلهٔ زنده با زبان خودت',setupHeading:'برای شروع فقط یک کلید لازم داری',setupDescription:'کلید Gemini را از Google AI Studio بگیر، اینجا Paste کن و ادامه بده.',setupGetKey:'دریافت Gemini API key',setupSave:'ذخیره و ادامه',setupChecking:'در حال بررسی کلید…',setupMissing:'اول کلید API را Paste کنید.',setupInvalid:'کلید تأیید نشد. کلید، سهمیه و اینترنت را بررسی کنید.',setupTrust:'کلید API شما فقط روی همین دستگاه ذخیره می‌شود و مستقیماً برای اتصال به Google Gemini استفاده می‌شود.'});
Object.assign(translations.en,{setupWelcome:'Live dubbing in your language',setupHeading:'One key is all you need to start',setupDescription:'Get a Gemini key from Google AI Studio, paste it here, and continue.',setupGetKey:'Get Gemini API key',setupSave:'Save & Continue',setupChecking:'Checking your key…',setupMissing:'Paste your API key first.',setupInvalid:'We could not verify this key. Check the key, quota, and connection.',setupTrust:'Your API key is stored locally on your device and is used to connect directly to Google Gemini.'});
Object.assign(translations.fa,{voiceNav:'تایپ صوتی',voiceTitle:'تایپ صوتی',voiceDescription:'با صحبت‌کردن، متن را در هر فیلد وب وارد کنید.',voiceEnable:'فعال‌کردن تایپ صوتی',voiceDisable:'غیرفعال‌کردن تایپ صوتی',voiceHint:'فعال‌سازی فقط کنترل شناور را روی صفحه می‌آورد. میکروفن و ارسال صدا فقط وقتی شروع می‌شوند که خودتان «شروع» را روی کنترل بزنید.',voiceHowTitle:'چطور کار می‌کند؟',voiceStep1:'تایپ صوتی را روی صفحهٔ وب فعال کنید.',voiceStep2:'داخل input، textarea یا بخش قابل‌ویرایش کلیک و روی کنترل شناور «شروع» را بزنید.',voiceStep3:'با توقف، متن نهایی درج می‌شود و امکان درج دستی، کپی و حذف هم دارید.',voicePrivacy:'صدای میکروفن با کلید شما مستقیماً برای رونویسی به Google Gemini Transcribe Live می‌رود. صدا، متن و کلید از سرورهای Dubly عبور نمی‌کنند و روی آن‌ها ذخیره نمی‌شوند.',voiceDisabled:'تایپ صوتی غیرفعال است',voiceReady:'تایپ صوتی روی صفحه آماده است',voiceConnecting:'در حال اتصال به Google…',voiceListening:'در حال شنیدن',voiceEnableError:'تایپ صوتی فعال نشد. اجازهٔ میکروفن را بدهید و یک صفحهٔ معمولی وب باز کنید؛ صفحات داخلی Chrome پشتیبانی نمی‌شوند.'});
Object.assign(translations.en,{voiceNav:'Voice Typing',voiceTitle:'Voice Typing',voiceDescription:'Speak to enter text in fields across the web.',voiceEnable:'Enable Voice Typing',voiceDisable:'Disable Voice Typing',voiceHint:'Enabling only adds the floating control. Microphone capture and transmission begin only when you press Start on that control.',voiceHowTitle:'How it works',voiceStep1:'Enable Voice Typing on a web page.',voiceStep2:'Click an input, textarea, or editable area and press Start on the floating control.',voiceStep3:'Stopping inserts the final text; you can also insert manually, copy, or delete it.',voicePrivacy:'Microphone audio is sent with your key directly to Google Gemini Transcribe Live for transcription. Audio, text, and the key never pass through or are stored on Dubly servers.',voiceDisabled:'Voice Typing is off',voiceReady:'Voice Typing is ready on this page',voiceConnecting:'Connecting to Google…',voiceListening:'Listening',voiceEnableError:'Could not enable Voice Typing. Allow microphone access and open a regular web page; Chrome internal pages are unsupported.'});
Object.assign(translations.fa,{voiceCurrentSite:'سایت فعلی',voiceUnsupportedSite:'این صفحه پشتیبانی نمی‌شود',voicePermissionWindow:'پنجرهٔ اجازهٔ میکروفن باز شد؛ اجازه را تأیید کنید.'});
Object.assign(translations.en,{voiceCurrentSite:'Current website',voiceUnsupportedSite:'This page is not supported',voicePermissionWindow:'The microphone permission window is open. Confirm access there.'});
Object.assign(translations.fa,{voiceSiteAccessRequired:'برای فعال‌ماندن تایپ صوتی هنگام جابه‌جایی همان تب، اجازهٔ دسترسی به سایت‌ها را تأیید کنید.'});
Object.assign(translations.en,{voiceSiteAccessRequired:'Allow website access so Voice Typing can remain active when this tab navigates.'});
englishErrors.push(['ویدیوی قابل دسترس پیدا نشد. ویدیو را پخش کنید یا صفحهٔ اصلی پخش‌کننده را باز کنید.','No accessible video found. Play the video or open the player’s original page.']);
englishErrors.push(['Voice Typing را روی یک صفحهٔ معمولی وب باز کنید؛ صفحات داخلی Chrome پشتیبانی نمی‌شوند.','Open Voice Typing on a regular web page. Chrome internal pages are unsupported.']);
englishErrors.push(['Voice Typing را روی یک صفحهٔ وب باز کنید.','Open Voice Typing on a web page.']);
